name: ListenMode
version: ${project.version}
main: me.matsubara.listenmode.ListenModePlugin
api-version: 1.17
author: Matsubara
description: ${project.description}
depend:
  - packetevents
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - Vault
libraries:
  - org.apache.commons:commons-lang3:3.14.0
  - commons-io:commons-io:2.15.1

commands:
  listenmode:
    description: main command.
    usage: /<command>
    aliases:
      - lm
      - lmode